### ISSUE TITLE
只能破滑块的？

### ISSUE THREAD

**Issue by draco1023** [Hsury/Geetest3-Crack#1]
如题

**Comment by Hsury** [comment]
目前仅实现了滑动模式的自动破解，点选模式需要人工参与。

**Comment by mengpengfei** [comment]
你的轨迹算法我看了，会被封

**Comment by mengpengfei** [comment]
加我qq吧3455473568，我有另外的破解方式，轨迹的处理跟你不一样，可以交流下，另外点选类型的我已经用深度学习破解了

**Comment by Hsury** [comment]
这套轨迹算法目前能实现高于80%的单次通过率喔！

**Comment by Hsury** [comment]
若有更优秀的轨迹算法或点选解决方案，欢迎直接提交PR~
