### ISSUE TITLE
b站使用的极验系统又一次调整验证码策略之后，当前轨迹失效

### ISSUE THREAD

**Issue by yjqiang** [Hsury/Geetest3-Crack#3]
如题，出现概率高达70%+，基本没法用

**Comment by Hsury** [comment]
是的，目前使用的轨迹算法已经被极验特征识别了，导致通过率下降。

**Comment by yjqiang** [comment]
> 是的，目前使用的轨迹算法已经被极验特征识别了，导致通过率下降。

有破解的办法么，试了不少了，都不行了

**Comment by Hsury** [comment]
有一个思路：随机抓取一批拼图（能覆盖越多的滑动距离越好），然后真人滑动产生足够的数据集来训练一个输入缺口距离，输出轨迹数组的神经网络。大佬可以尝试做一做~

**Comment by yjqiang** [comment]
> 有一个思路：随机抓取一批拼图（能覆盖越多的滑动距离越好），然后真人滑动产生足够的数据集来训练一个输入缺口距离，输出轨迹数组的神经网络。大佬可以尝试做一做~

你在玩蛇呢。。。不可能的，工作量太大了

**Comment by Hsury** [comment]
退而求其次就是再调出一个可用的轨迹算法，不过这样被识别还是迟早的事。要么就是直接上JS爆破叭= =

**Comment by yjqiang** [comment]
可能无限推迟这个计划了，不过你的这个东西辅助学习js不错，你能不能稍微详细说一下架构调用？就是整个执行run.py流程，以及稍微讲一下js执行过程。我感觉我js学的一坨💩

**Comment by Hsury** [comment]
run.py只是一个启动器啦，读取配置文件然后按需启动各个组件。
建议先熟悉下[极验验证通讯流程图](https://docs.geetest.com/install/overview/flowchart/)。
本项目将“核心验证过程”这一环节从要求进行验证的网站中抽离了出来，这样也就实现了最小资源加载验证码。这一部分主要由static/geetest.html实现，工人worker.py使用Selenium控制ChromeDriver显示该页面，它将持续向服务端server.py请求任务。
服务端维护了一个任务队列，此时用户提交识别任务至服务端API，服务端便会生成一个会话ID，与gt与challenge一同返回给页面。
页面调用gt.js加载出验证码窗口，此时便会触发工人使用预设的轨迹算法自动拖动滑块完成拼图。
之后滑动数据会被上传至极验服务器进行人机判断，页面再将极验服务器返回的二次验证数据challenge、validate与seccode或是拒绝验证的消息与会话ID一同回传给服务端API，服务端再将数据返回给用户。

**Comment by Hsury** [comment]
呃，突然发现这个Issue的标题有点问题。对滑动轨迹是否有效的判定是由极验方面完成的而并非B站。B站只是极验的付费客户，对接了极验滑动验证系统并定制了背景图而已~

**Comment by mengpengfei** [comment]
老弟你测试了没有，到底是轨迹被封了还是ip被封了

**Comment by yjqiang** [comment]
> 老弟你测试了没有，到底是轨迹被封了还是ip被封了

轨迹

**Comment by mengpengfei** [comment]
轨迹可以微调下就行了，有没有办法生成批量无穷的抛物线

**Comment by yjqiang** [comment]
> 轨迹可以微调下就行了，有没有办法生成批量无穷的抛物线

自己去调  我调了半天 都不行

**Comment by yjqiang** [comment]
> run.py只是一个启动器啦，读取配置文件然后按需启动各个组件。
> 建议先熟悉下[极验验证通讯流程图](https://docs.geetest.com/install/overview/flowchart/)。
> 本项目将“核心验证过程”这一环节从要求进行验证的网站中抽离了出来，这样也就实现了最小资源加载验证码。这一部分主要由static/geetest.html实现，工人worker.py使用Selenium控制ChromeDriver显示该页面，它将持续向服务端server.py请求任务。
> 服务端维护了一个任务队列，此时用户提交识别任务至服务端API，服务端便会生成一个会话ID，与gt与challenge一同返回给页面。
> 页面调用gt.js加载出验证码窗口，此时便会触发工人使用预设的轨迹算法自动拖动滑块完成拼图。
> 之后滑动数据会被上传至极验服务器进行人机判断，页面再将极验服务器返回的二次验证数据challenge、validate与seccode或是拒绝验证的消息与会话ID一同回传给服务端API，服务端再将数据返回给用户。

看了看，还是不太理解
https://github.com/Hsury/Geetest3-Crack/blob/master/test.py#L10 这里获取了gt、challenge、success，传入https://github.com/Hsury/Geetest3-Crack/blob/master/static/geetest.html#L41 ，  
 https://github.com/Hsury/Geetest3-Crack/blob/master/static/geetest.html#L65 这里应该是验证码出现吧。为什么我执行到这里，不出现验证码，直接显示成功？返回数据显示调用了https://github.com/Hsury/Geetest3-Crack/blob/master/static/geetest.html#L66 这里。
数据为

challenge: 5642d6df50fbd94454b3983aa88950af

validate: 2a53fc7836dd863ecdb4be9b94b15812

seccode: 2a53fc7836dd863ecdb4be9b94b15812|jordan

**Comment by yjqiang** [comment]
我想完成的东西就是根据b站返回的gt、challenge、success，在服务器端生成html页面，内部包含验证码，然后服务器端进行破解。但是目前验证码显示不出来。

**Comment by Hsury** [comment]
拼图加载不出来极有可能是因为你这个接口使用的是极验二代而不是三代= =

**Comment by yjqiang** [comment]
> 拼图加载不出来极有可能是因为你这个接口使用的是极验二代而不是三代= =

我似乎搞到你qq了……你看看加一下我

**Comment by mengpengfei** [comment]
我做了一个打码平台，通杀极验验证码和英数验证码，有兴趣可以去看看 http://www.damagou.top

**Comment by yjqiang** [comment]
> 我做了一个打码平台，通杀极验验证码和英数验证码，有兴趣可以去看看 http://www.damagou.top

并不觉得api调用比较简洁，建议使用key的办法去完成，以及可以使用key去进行加密或者直接https，用户名加密码的方式过于繁琐，并不适合直接调用。如果api很方便的话，倒是可以考虑对接。但是这是他人的repo，建议不要直接打广告

**Comment by mengpengfei** [comment]
> > 我做了一个打码平台，通杀极验验证码和英数验证码，有兴趣可以去看看 http://www.damagou.top
> 
> 并不觉得api调用比较简洁，建议使用key的办法去完成，以及可以使用key去进行加密或者直接https，用户名加密码的方式过于繁琐，并不适合直接调用。如果api很方便的话，倒是可以考虑对接。但是这是他人的repo，建议不要直接打广告

调用很简单，可以参考下，就是一个post，哈哈，不打广告不打广告了

**Comment by yjqiang** [comment]
> > > 我做了一个打码平台，通杀极验验证码和英数验证码，有兴趣可以去看看 http://www.damagou.top
> > 
> > 并不觉得api调用比较简洁，建议使用key的办法去完成，以及可以使用key去进行加密或者直接https，用户名加密码的方式过于繁琐，并不适合直接调用。如果api很方便的话，倒是可以考虑对接。但是这是他人的repo，建议不要直接打广告
> 
> 调用很简单，可以参考下，就是一个post，哈哈，不打广告不打广告了

似乎需要密码之类的，不太方便，如果可以做到key这种，我还是很乐意加入支持的。

**Comment by mengpengfei** [comment]
> > > > 我做了一个打码平台，通杀极验验证码和英数验证码，有兴趣可以去看看 http://www.damagou.top
> > > 
> > > 
> > > 并不觉得api调用比较简洁，建议使用key的办法去完成，以及可以使用key去进行加密或者直接https，用户名加密码的方式过于繁琐，并不适合直接调用。如果api很方便的话，倒是可以考虑对接。但是这是他人的repo，建议不要直接打广告
> > 
> > 
> > 调用很简单，可以参考下，就是一个post，哈哈，不打广告不打广告了
> 
> 似乎需要密码之类的，不太方便，如果可以做到key这种，我还是很乐意加入支持的。

只要用api登录一次就能得到一个key了，然后根据key调用就行了

**Comment by yjqiang** [comment]
> > > > > 我做了一个打码平台，通杀极验验证码和英数验证码，有兴趣可以去看看 http://www.damagou.top
> > > > 
> > > > 
> > > > 并不觉得api调用比较简洁，建议使用key的办法去完成，以及可以使用key去进行加密或者直接https，用户名加密码的方式过于繁琐，并不适合直接调用。如果api很方便的话，倒是可以考虑对接。但是这是他人的repo，建议不要直接打广告
> > > 
> > > 
> > > 调用很简单，可以参考下，就是一个post，哈哈，不打广告不打广告了
> > 
> > 似乎需要密码之类的，不太方便，如果可以做到key这种，我还是很乐意加入支持的。
> 
> 只要用api登录一次就能得到一个key了，然后根据key调用就行了

我联系你qq吧，就网页上的对吧，咱俩把信息删一下，别搞得跟小广告似得

**Comment by cjcj5243** [comment]
大佬们请教一下，https://github.com/Hsury/Geetest3-Crack/blob/c5298442bd75eb3f91047ffb552d91affd41ad4f/test.py#L21 为啥选取plat=5，我看实际上plat=2，而我在代码里改了=2后，却无法加载验证码了，请问是什么原因呢？

**Comment by yjqiang** [comment]
> 大佬们请教一下，https://github.com/Hsury/Geetest3-Crack/blob/c5298442bd75eb3f91047ffb552d91affd41ad4f/test.py#L21 为啥选取plat=5，我看实际上plat=2，而我在代码里改了=2后，却无法加载验证码了，请问是什么原因呢？

b站的geetest是混合的，有v3有v2，其中登录不清楚为什么一直v2

**Comment by cjcj5243** [comment]
> 
> 
> > 大佬们请教一下，
> >   
> >     
> >       [Geetest3-Crack/test.py](https://github.com/Hsury/Geetest3-Crack/blob/c5298442bd75eb3f91047ffb552d91affd41ad4f/test.py#L21)
> >     
> >     
> >          Line 21
> >       in
> >       [c529844](/Hsury/Geetest3-Crack/commit/c5298442bd75eb3f91047ffb552d91affd41ad4f)
> >     
> >     
> >     
> >     
> > 
> >         
> >           
> >            response = requests.get("https://passport.bilibili.com/web/captcha/combine?plat=5").json() 
> >         
> >     
> >   
> > 
> >  为啥选取plat=5，我看实际上plat=2，而我在代码里改了=2后，却无法加载验证码了，请问是什么原因呢？
> 
> b站的geetest是混合的，有v3有v2，其中登录不清楚为什么一直v2


那再请教一下如何区分v3和v2啊，在下面的代码里
https://github.com/Hsury/Geetest3-Crack/blob/c5298442bd75eb3f91047ffb552d91affd41ad4f/static/geetest.html#L51

我将new_captcha改为false也还是不行啊

**Comment by yjqiang** [comment]
> > 
> > 
> > > 大佬们请教一下，
> > >   
> > >     
> > >       [Geetest3-Crack/test.py](https://github.com/Hsury/Geetest3-Crack/blob/c5298442bd75eb3f91047ffb552d91affd41ad4f/test.py#L21)
> > >     
> > >     
> > >          Line 21
> > >       in
> > >       [c529844](/Hsury/Geetest3-Crack/commit/c5298442bd75eb3f91047ffb552d91affd41ad4f)
> > >     
> > >     
> > >     
> > >     
> > > 
> > >         
> > >           
> > >            response = requests.get("https://passport.bilibili.com/web/captcha/combine?plat=5").json() 
> > >         
> > >     
> > >   
> > > 
> > >  为啥选取plat=5，我看实际上plat=2，而我在代码里改了=2后，却无法加载验证码了，请问是什么原因呢？
> > 
> > b站的geetest是混合的，有v3有v2，其中登录不清楚为什么一直v2
> 
> 
> 那再请教一下如何区分v3和v2啊，在下面的代码里
> https://github.com/Hsury/Geetest3-Crack/blob/c5298442bd75eb3f91047ffb552d91affd41ad4f/static/geetest.html#L51
> 
> 我将new_captcha改为false也还是不行啊
> 
> 又看了一下，new_captcha是在宕机情况下起作用

现在的repo里面用的就是v3，v3的文档在geetest里面有，很简单就能调用。v2不能直接搞v3，虽然两者参数好像一样的。以及建议另开一个issue，别搞我的这个issue了吧……

**Comment by yjqiang** [comment]
@cjcj5243 你把comment删一下吧。以后提问新开一个issue，不然别人查看搜索都没法找主题。
