### ISSUE TITLE
How to find domain custom url like https://passport.bilibili.com/web/captcha/combine?plat=5

### ISSUE THREAD

**Issue by DinhCongTac221** [Hsury/Geetest3-Crack#4]
Hello Hsury,
I look into test.py .
I see url : https://passport.bilibili.com/web/captcha/combine?plat=5
It contains  gt,challenge,key.
How do i can find similar it with another site?
or how do i can find gt, changege key on a site?
thanks

**Comment by Hsury** [comment]
You can use Chrome DevTools or other packet capture software to monitor the page loading process and use keywords like gt and challenge to filter these packets. Then you will easily find out who is giving these parameters.
