### ISSUE TITLE
jsonp 格式的，应该怎么获取gt

### ISSUE THREAD

**Issue by jiangfeng0103** [Hsury/Geetest3-Crack#5]
$.ajax({
            url: "http://login.jiayuan.com/geetest_init.php?jsonCallBack&t=" + (new Date()).getTime(),
            type: "get",
            dataType: "jsonp",
            jsonp: 'jsonCallBack',
            success: function (data) {
                initGeetest({
                    gt: data.gt,
                    challenge: data.challenge,
                    offline: !data.success,
                    new_captcha: data.new_captcha,
                    product: "bind",
                    width: "300px",
                    https: true
                }, handlerEmbed);
            }
        });

这个网站是用 Jsonp 获取 获取gt的

        response = requests.get("http://login.jiayuan.com/geetest_init.php")，这样获取不到gt

**Comment by Hsury** [comment]
将首部的"("与尾部的");"去除，中间部分就是Python可解析的标准JSON字符串了
`params = json.loads(response.text[1:-2])`

**Comment by jiangfeng0103** [comment]
response = requests.get("http://login.jiayuan.com/geetest_init.php")
print(response)
response 的返回值是 <Response [200]>， 这个请求应该是出错了

**Comment by jiangfeng0103** [comment]
解决了 谢谢
